
app.bootstrap.admin-email=${APP_ADMIN_EMAIL:admin@wildlife.local}
app.bootstrap.admin-password=${APP_ADMIN_PASSWORD:Admin123!}
app.bootstrap.customer-email=${APP_CUSTOMER_EMAIL:customer@wildlife.local}
app.bootstrap.customer-password=${APP_CUSTOMER_PASSWORD:Customer123!}
